name: ido
description: "A new Flutter project."
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev


version: 1.0.0+1

environment:
  sdk: ^3.6.1


dependencies:
  flutter:
    sdk: flutter
  google_fonts: ^6.3.0

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.8
  curved_navigation_bar: ^1.0.6
  http: ^1.5.0
  shared_preferences: ^2.5.3
  yandex_mapkit: ^4.1.0
  flutter_localizations:
    sdk: flutter
  flutter_typeahead: ^5.2.0
  image_picker: ^1.2.0
  flutter_image_compress: ^2.4.0
  path_provider: ^2.1.5
  font_awesome_flutter: ^10.9.1
  url_launcher: ^6.3.2
  

dev_dependencies:
  flutter_test:
    sdk: flutter


  flutter_lints: ^5.0.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true
